<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div class="g-recaptcha" data-sitekey="<?php echo $apiKey; ?>"></div>
<noscript>
	<iframe src="https://www.google.com/recaptcha/api/fallback?k=<?php echo $apiKey; ?>" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
	<div style="width: 300px; height: 60px; border-style: none;bottom: 12px; left: 25px; margin: -10px 0 0 0; padding: 0px; right: 25px;background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
		<textarea data-novalidate="" id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1;margin: 10px 25px; padding: 0px; resize: none;" ></textarea>
	</div>
</noscript>